name: Staging Pipeline (Offline Test)
on:
  push:
    branches: [staging]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Pipeline complete
        run: echo "✅ Staging pipeline completed successfully (offline test)"
